name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Open the game...
        2. Go to...
        3. Click on...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the project is affected?
      options:
        - Combat System
        - Caravan/Party Management
        - Map/Exploration
        - Editor/Tooling
        - Mod System
        - Save/Load
        - UI/Menus
        - Audio
        - Other
    validations:
      required: true

  - type: input
    id: godot-version
    attributes:
      label: Godot Version
      description: Which version of Godot are you using?
      placeholder: "e.g., 4.5.1"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true

  - type: textarea
    id: mods
    attributes:
      label: Active Mods
      description: List any mods you have enabled (if applicable)
      placeholder: |
        - demo_campaign
        - my_custom_mod

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant error messages from the Godot console
      render: shell

  - type: textarea
    id: mrp
    attributes:
      label: Minimal Reproduction Project
      description: If possible, link to a minimal project that reproduces the issue
      placeholder: Link to a GitHub repo or zip file...

  - type: checkboxes
    id: search
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't already been reported
          required: true
